// AUTO-GENERATED by scripts/gen-chat-media.mjs — do not edit by hand.
// The server-approved whitelist of chat sticker media (Stage 11.0). Pure data:
// no Node/React, importable by BOTH the server (validation) and the client (UI).
// A chat client may only reference a media item by its `id`; the server resolves
// the id here and broadcasts the approved { id, src, type, label } — never a
// client-supplied src/url.

export type ChatMediaType = 'gif' | 'image';

export interface ChatMediaItem {
  id: string;
  /** Served from public/chat-media/ — always starts with '/chat-media/'. */
  src: string;
  type: ChatMediaType;
  label: string;
}

export const CHAT_MEDIA: ChatMediaItem[] = [
  {
    "id": "burn",
    "src": "/chat-media/burn.gif",
    "type": "gif",
    "label": "Burn"
  },
  {
    "id": "bit",
    "src": "/chat-media/bit.gif",
    "type": "gif",
    "label": "Bit"
  },
  {
    "id": "eat",
    "src": "/chat-media/eat.gif",
    "type": "gif",
    "label": "Eat"
  },
  {
    "id": "heart",
    "src": "/chat-media/heart.gif",
    "type": "gif",
    "label": "Heart"
  },
  {
    "id": "nyabeach",
    "src": "/chat-media/nyabeach.png",
    "type": "image",
    "label": "Nya Beach"
  },
  {
    "id": "nyabeanie",
    "src": "/chat-media/nyabeanie.png",
    "type": "image",
    "label": "Nya Beanie"
  },
  {
    "id": "nyabee",
    "src": "/chat-media/nyabee.png",
    "type": "image",
    "label": "Nya Bee"
  },
  {
    "id": "nyablush",
    "src": "/chat-media/nyablush.png",
    "type": "image",
    "label": "Nya Blush"
  },
  {
    "id": "nyablushing",
    "src": "/chat-media/nyablushing.gif",
    "type": "gif",
    "label": "Nya Blushing"
  },
  {
    "id": "nyaboba3",
    "src": "/chat-media/nyaboba3.gif",
    "type": "gif",
    "label": "Nya Boba 3"
  },
  {
    "id": "nyaboba-1",
    "src": "/chat-media/nyaboba-1.gif",
    "type": "gif",
    "label": "Nya Boba 1"
  },
  {
    "id": "nyabored",
    "src": "/chat-media/nyabored.gif",
    "type": "gif",
    "label": "Nya Bored"
  },
  {
    "id": "nyabored2",
    "src": "/chat-media/nyabored2.gif",
    "type": "gif",
    "label": "Nya Bored 2"
  },
  {
    "id": "nyabreakfast",
    "src": "/chat-media/nyabreakfast.gif",
    "type": "gif",
    "label": "Nya Breakfast"
  },
  {
    "id": "nyabrush",
    "src": "/chat-media/nyabrush.gif",
    "type": "gif",
    "label": "Nya Brush"
  },
  {
    "id": "nyabully",
    "src": "/chat-media/nyabully.gif",
    "type": "gif",
    "label": "Nya Bully"
  },
  {
    "id": "nyaburger",
    "src": "/chat-media/nyaburger.png",
    "type": "image",
    "label": "Nya Burger"
  },
  {
    "id": "nyabutt",
    "src": "/chat-media/nyabutt.png",
    "type": "image",
    "label": "Nya Butt"
  },
  {
    "id": "nyacake",
    "src": "/chat-media/nyacake.png",
    "type": "image",
    "label": "Nya Cake"
  },
  {
    "id": "nyacheer",
    "src": "/chat-media/nyacheer.gif",
    "type": "gif",
    "label": "Nya Cheer"
  },
  {
    "id": "nyachick",
    "src": "/chat-media/nyachick.png",
    "type": "image",
    "label": "Nya Chick"
  },
  {
    "id": "nyachicks",
    "src": "/chat-media/nyachicks.png",
    "type": "image",
    "label": "Nya Chicks"
  },
  {
    "id": "nyachill",
    "src": "/chat-media/nyachill.gif",
    "type": "gif",
    "label": "Nya Chill"
  },
  {
    "id": "nyachill1",
    "src": "/chat-media/nyachill1.png",
    "type": "image",
    "label": "Nya Chill 1"
  },
  {
    "id": "nyachill2",
    "src": "/chat-media/nyachill2.gif",
    "type": "gif",
    "label": "Nya Chill 2"
  },
  {
    "id": "nyachips",
    "src": "/chat-media/nyachips.png",
    "type": "image",
    "label": "Nya Chips"
  },
  {
    "id": "nyachips-1",
    "src": "/chat-media/nyachips-1.gif",
    "type": "gif",
    "label": "Nya Chips 1"
  },
  {
    "id": "nyachonk",
    "src": "/chat-media/nyachonk.gif",
    "type": "gif",
    "label": "Nya Chonk"
  },
  {
    "id": "nyachonk1",
    "src": "/chat-media/nyachonk1.gif",
    "type": "gif",
    "label": "Nya Chonk 1"
  },
  {
    "id": "nyachonk2",
    "src": "/chat-media/nyachonk2.gif",
    "type": "gif",
    "label": "Nya Chonk 2"
  },
  {
    "id": "nyaclover",
    "src": "/chat-media/nyaclover.png",
    "type": "image",
    "label": "Nya Clover"
  },
  {
    "id": "nyacold",
    "src": "/chat-media/nyacold.png",
    "type": "image",
    "label": "Nya Cold"
  },
  {
    "id": "nyacomfy",
    "src": "/chat-media/nyacomfy.gif",
    "type": "gif",
    "label": "Nya Comfy"
  },
  {
    "id": "nyacook2",
    "src": "/chat-media/nyacook2.png",
    "type": "image",
    "label": "Nya Cook 2"
  },
  {
    "id": "nyacool",
    "src": "/chat-media/nyacool.gif",
    "type": "gif",
    "label": "Nya Cool"
  },
  {
    "id": "nyacozy",
    "src": "/chat-media/nyacozy.png",
    "type": "image",
    "label": "Nya Cozy"
  },
  {
    "id": "nyacozy1",
    "src": "/chat-media/nyacozy1.png",
    "type": "image",
    "label": "Nya Cozy 1"
  },
  {
    "id": "nyacry",
    "src": "/chat-media/nyacry.gif",
    "type": "gif",
    "label": "Nya Cry"
  },
  {
    "id": "nyacry1",
    "src": "/chat-media/nyacry1.gif",
    "type": "gif",
    "label": "Nya Cry 1"
  },
  {
    "id": "nyacryinpain",
    "src": "/chat-media/nyacryinpain.gif",
    "type": "gif",
    "label": "Nya Cryinpain"
  },
  {
    "id": "nyacute1",
    "src": "/chat-media/nyacute1.png",
    "type": "image",
    "label": "Nya Cute 1"
  },
  {
    "id": "nyacute2",
    "src": "/chat-media/nyacute2.gif",
    "type": "gif",
    "label": "Nya Cute 2"
  },
  {
    "id": "nyacute3",
    "src": "/chat-media/nyacute3.gif",
    "type": "gif",
    "label": "Nya Cute 3"
  },
  {
    "id": "nyacute4",
    "src": "/chat-media/nyacute4.gif",
    "type": "gif",
    "label": "Nya Cute 4"
  },
  {
    "id": "nyacuteaww",
    "src": "/chat-media/nyacuteaww.gif",
    "type": "gif",
    "label": "Nya Cuteaww"
  },
  {
    "id": "nyacutebunny",
    "src": "/chat-media/nyacutebunny.png",
    "type": "image",
    "label": "Nya Cutebunny"
  },
  {
    "id": "nyacutecat",
    "src": "/chat-media/nyacutecat.png",
    "type": "image",
    "label": "Nya Cutecat"
  },
  {
    "id": "nyacutepaws",
    "src": "/chat-media/nyacutepaws.png",
    "type": "image",
    "label": "Nya Cutepaws"
  },
  {
    "id": "nyadance",
    "src": "/chat-media/nyadance.gif",
    "type": "gif",
    "label": "Nya Dance"
  },
  {
    "id": "nyaded",
    "src": "/chat-media/nyaded.gif",
    "type": "gif",
    "label": "Nya Ded"
  },
  {
    "id": "nyadevil",
    "src": "/chat-media/nyadevil.png",
    "type": "image",
    "label": "Nya Devil"
  },
  {
    "id": "nyadonut",
    "src": "/chat-media/nyadonut.png",
    "type": "image",
    "label": "Nya Donut"
  },
  {
    "id": "nyadonut2",
    "src": "/chat-media/nyadonut2.png",
    "type": "image",
    "label": "Nya Donut 2"
  },
  {
    "id": "nyadonut3",
    "src": "/chat-media/nyadonut3.png",
    "type": "image",
    "label": "Nya Donut 3"
  },
  {
    "id": "nyadraw",
    "src": "/chat-media/nyadraw.png",
    "type": "image",
    "label": "Nya Draw"
  },
  {
    "id": "nyadrool",
    "src": "/chat-media/nyadrool.gif",
    "type": "gif",
    "label": "Nya Drool"
  },
  {
    "id": "nyaeat",
    "src": "/chat-media/nyaeat.gif",
    "type": "gif",
    "label": "Nya Eat"
  },
  {
    "id": "nyaeeh",
    "src": "/chat-media/nyaeeh.png",
    "type": "image",
    "label": "Nya Eeh"
  },
  {
    "id": "nyaeggtoast",
    "src": "/chat-media/nyaeggtoast.png",
    "type": "image",
    "label": "Nya Eggtoast"
  },
  {
    "id": "nyaevilqueen",
    "src": "/chat-media/nyaevilqueen.png",
    "type": "image",
    "label": "Nya Evilqueen"
  },
  {
    "id": "nyaexercise",
    "src": "/chat-media/nyaexercise.png",
    "type": "image",
    "label": "Nya Exercise"
  },
  {
    "id": "nyafan",
    "src": "/chat-media/nyafan.png",
    "type": "image",
    "label": "Nya Fan"
  },
  {
    "id": "nyafan2",
    "src": "/chat-media/nyafan2.gif",
    "type": "gif",
    "label": "Nya Fan 2"
  },
  {
    "id": "nyaflick",
    "src": "/chat-media/nyaflick.gif",
    "type": "gif",
    "label": "Nya Flick"
  },
  {
    "id": "nyaflick2",
    "src": "/chat-media/nyaflick2.png",
    "type": "image",
    "label": "Nya Flick 2"
  },
  {
    "id": "nyaflowers",
    "src": "/chat-media/nyaflowers.png",
    "type": "image",
    "label": "Nya Flowers"
  },
  {
    "id": "nyafries",
    "src": "/chat-media/nyafries.png",
    "type": "image",
    "label": "Nya Fries"
  },
  {
    "id": "nyaghost1",
    "src": "/chat-media/nyaghost1.png",
    "type": "image",
    "label": "Nya Ghost 1"
  },
  {
    "id": "nyaghost2",
    "src": "/chat-media/nyaghost2.png",
    "type": "image",
    "label": "Nya Ghost 2"
  },
  {
    "id": "nyagingerbread",
    "src": "/chat-media/nyagingerbread.png",
    "type": "image",
    "label": "Nya Gingerbread"
  },
  {
    "id": "nyaglasses",
    "src": "/chat-media/nyaglasses.gif",
    "type": "gif",
    "label": "Nya Glasses"
  },
  {
    "id": "nyaglasses-1",
    "src": "/chat-media/nyaglasses-1.png",
    "type": "image",
    "label": "Nya Glasses 1"
  },
  {
    "id": "nyagraduation",
    "src": "/chat-media/nyagraduation.png",
    "type": "image",
    "label": "Nya Graduation"
  },
  {
    "id": "nyahappy",
    "src": "/chat-media/nyahappy.gif",
    "type": "gif",
    "label": "Nya Happy"
  },
  {
    "id": "nyaheart",
    "src": "/chat-media/nyaheart.gif",
    "type": "gif",
    "label": "Nya Heart"
  },
  {
    "id": "nyahearts",
    "src": "/chat-media/nyahearts.png",
    "type": "image",
    "label": "Nya Hearts"
  },
  {
    "id": "nyahehe",
    "src": "/chat-media/nyahehe.gif",
    "type": "gif",
    "label": "Nya Hehe"
  },
  {
    "id": "nyahelp",
    "src": "/chat-media/nyahelp.gif",
    "type": "gif",
    "label": "Nya Help"
  },
  {
    "id": "nyahmph1",
    "src": "/chat-media/nyahmph1.gif",
    "type": "gif",
    "label": "Nya Hmph 1"
  },
  {
    "id": "nyahmph2",
    "src": "/chat-media/nyahmph2.png",
    "type": "image",
    "label": "Nya Hmph 2"
  },
  {
    "id": "nyahungry",
    "src": "/chat-media/nyahungry.gif",
    "type": "gif",
    "label": "Nya Hungry"
  },
  {
    "id": "nyahype",
    "src": "/chat-media/nyahype.gif",
    "type": "gif",
    "label": "Nya Hype"
  },
  {
    "id": "nyahype2",
    "src": "/chat-media/nyahype2.gif",
    "type": "gif",
    "label": "Nya Hype 2"
  },
  {
    "id": "nyahyperspin",
    "src": "/chat-media/nyahyperspin.gif",
    "type": "gif",
    "label": "Nya Hyperspin"
  },
  {
    "id": "nyahyperyay",
    "src": "/chat-media/nyahyperyay.gif",
    "type": "gif",
    "label": "Nya Hyperyay"
  },
  {
    "id": "nyaily",
    "src": "/chat-media/nyaily.gif",
    "type": "gif",
    "label": "Nya ILY"
  },
  {
    "id": "nyaicecream",
    "src": "/chat-media/nyaicecream.png",
    "type": "image",
    "label": "Nya Icecream"
  },
  {
    "id": "nyaicecream1",
    "src": "/chat-media/nyaicecream1.png",
    "type": "image",
    "label": "Nya Icecream 1"
  },
  {
    "id": "nyaicecream2",
    "src": "/chat-media/nyaicecream2.png",
    "type": "image",
    "label": "Nya Icecream 2"
  },
  {
    "id": "nyaignorework",
    "src": "/chat-media/nyaignorework.gif",
    "type": "gif",
    "label": "Nya Ignorework"
  },
  {
    "id": "nyajam",
    "src": "/chat-media/nyajam.png",
    "type": "image",
    "label": "Nya Jam"
  },
  {
    "id": "nyakfc",
    "src": "/chat-media/nyakfc.gif",
    "type": "gif",
    "label": "Nya KFC"
  },
  {
    "id": "yay",
    "src": "/chat-media/yay.gif",
    "type": "gif",
    "label": "Yay"
  }
];

const BY_ID: ReadonlyMap<string, ChatMediaItem> = new Map(CHAT_MEDIA.map((m) => [m.id, m]));

/** The whitelisted media item for an id, or null. Used by the server to validate. */
export function getChatMedia(id: unknown): ChatMediaItem | null {
  return typeof id === 'string' ? (BY_ID.get(id) ?? null) : null;
}
