// AUTO-GENERATED by scripts/gen-chat-media.mjs — do not edit by hand.
// The server-approved whitelist of chat sticker media (Stage 11.0). Pure data:
// no Node/React, importable by BOTH the server (validation) and the client (UI).
// A chat client may only reference a media item by its `id`; the server resolves
// the id here and broadcasts the approved { id, src, type, label } — never a
// client-supplied src/url.

export type ChatMediaType = 'gif' | 'image';

export interface ChatMediaItem {
  id: string;
  /** Served from public/chat-media/ — always starts with '/chat-media/'. */
  src: string;
  type: ChatMediaType;
  label: string;
}

export const CHAT_MEDIA: ChatMediaItem[] = [
  {
    "id": "burn",
    "src": "/chat-media/burn.gif",
    "type": "gif",
    "label": "Burn"
  },
  {
    "id": "bit",
    "src": "/chat-media/bit.gif",
    "type": "gif",
    "label": "Bit"
  },
  {
    "id": "eat",
    "src": "/chat-media/eat.gif",
    "type": "gif",
    "label": "Eat"
  },
  {
    "id": "heart",
    "src": "/chat-media/heart.gif",
    "type": "gif",
    "label": "Heart"
  },
  {
    "id": "nyabeach",
    "src": "/chat-media/nyabeach.png",
    "type": "image",
    "label": "Nya Beach"
  },
  {
    "id": "nyabeanie",
    "src": "/chat-media/nyabeanie.png",
    "type": "image",
    "label": "Nya Beanie"
  },
  {
    "id": "nyabee",
    "src": "/chat-media/nyabee.png",
    "type": "image",
    "label": "Nya Bee"
  },
  {
    "id": "nyablush",
    "src": "/chat-media/nyablush.png",
    "type": "image",
    "label": "Nya Blush"
  },
  {
    "id": "nyablushing",
    "src": "/chat-media/nyablushing.gif",
    "type": "gif",
    "label": "Nya Blushing"
  },
  {
    "id": "nyaboba3",
    "src": "/chat-media/nyaboba3.gif",
    "type": "gif",
    "label": "Nya Boba 3"
  },
  {
    "id": "nyaboba-1",
    "src": "/chat-media/nyaboba-1.gif",
    "type": "gif",
    "label": "Nya Boba 1"
  },
  {
    "id": "nyabored",
    "src": "/chat-media/nyabored.gif",
    "type": "gif",
    "label": "Nya Bored"
  },
  {
    "id": "nyabored2",
    "src": "/chat-media/nyabored2.gif",
    "type": "gif",
    "label": "Nya Bored 2"
  },
  {
    "id": "nyabreakfast",
    "src": "/chat-media/nyabreakfast.gif",
    "type": "gif",
    "label": "Nya Breakfast"
  },
  {
    "id": "nyabrush",
    "src": "/chat-media/nyabrush.gif",
    "type": "gif",
    "label": "Nya Brush"
  },
  {
    "id": "nyabully",
    "src": "/chat-media/nyabully.gif",
    "type": "gif",
    "label": "Nya Bully"
  },
  {
    "id": "nyaburger",
    "src": "/chat-media/nyaburger.png",
    "type": "image",
    "label": "Nya Burger"
  },
  {
    "id": "nyabutt",
    "src": "/chat-media/nyabutt.png",
    "type": "image",
    "label": "Nya Butt"
  },
  {
    "id": "nyacake",
    "src": "/chat-media/nyacake.png",
    "type": "image",
    "label": "Nya Cake"
  },
  {
    "id": "nyacheer",
    "src": "/chat-media/nyacheer.gif",
    "type": "gif",
    "label": "Nya Cheer"
  },
  {
    "id": "nyachick",
    "src": "/chat-media/nyachick.png",
    "type": "image",
    "label": "Nya Chick"
  },
  {
    "id": "nyachicks",
    "src": "/chat-media/nyachicks.png",
    "type": "image",
    "label": "Nya Chicks"
  },
  {
    "id": "nyachill",
    "src": "/chat-media/nyachill.gif",
    "type": "gif",
    "label": "Nya Chill"
  },
  {
    "id": "nyachill1",
    "src": "/chat-media/nyachill1.png",
    "type": "image",
    "label": "Nya Chill 1"
  },
  {
    "id": "nyachill2",
    "src": "/chat-media/nyachill2.gif",
    "type": "gif",
    "label": "Nya Chill 2"
  },
  {
    "id": "nyachips",
    "src": "/chat-media/nyachips.png",
    "type": "image",
    "label": "Nya Chips"
  },
  {
    "id": "nyachips-1",
    "src": "/chat-media/nyachips-1.gif",
    "type": "gif",
    "label": "Nya Chips 1"
  },
  {
    "id": "nyachonk",
    "src": "/chat-media/nyachonk.gif",
    "type": "gif",
    "label": "Nya Chonk"
  },
  {
    "id": "nyachonk1",
    "src": "/chat-media/nyachonk1.gif",
    "type": "gif",
    "label": "Nya Chonk 1"
  },
  {
    "id": "nyachonk2",
    "src": "/chat-media/nyachonk2.gif",
    "type": "gif",
    "label": "Nya Chonk 2"
  },
  {
    "id": "nyaclover",
    "src": "/chat-media/nyaclover.png",
    "type": "image",
    "label": "Nya Clover"
  },
  {
    "id": "nyacold",
    "src": "/chat-media/nyacold.png",
    "type": "image",
    "label": "Nya Cold"
  },
  {
    "id": "nyacomfy",
    "src": "/chat-media/nyacomfy.gif",
    "type": "gif",
    "label": "Nya Comfy"
  },
  {
    "id": "nyacook2",
    "src": "/chat-media/nyacook2.png",
    "type": "image",
    "label": "Nya Cook 2"
  },
  {
    "id": "nyacool",
    "src": "/chat-media/nyacool.gif",
    "type": "gif",
    "label": "Nya Cool"
  },
  {
    "id": "nyacozy",
    "src": "/chat-media/nyacozy.png",
    "type": "image",
    "label": "Nya Cozy"
  },
  {
    "id": "nyacozy1",
    "src": "/chat-media/nyacozy1.png",
    "type": "image",
    "label": "Nya Cozy 1"
  },
  {
    "id": "nyacry",
    "src": "/chat-media/nyacry.gif",
    "type": "gif",
    "label": "Nya Cry"
  },
  {
    "id": "nyacry1",
    "src": "/chat-media/nyacry1.gif",
    "type": "gif",
    "label": "Nya Cry 1"
  },
  {
    "id": "nyacryinpain",
    "src": "/chat-media/nyacryinpain.gif",
    "type": "gif",
    "label": "Nya Cryinpain"
  },
  {
    "id": "nyacute1",
    "src": "/chat-media/nyacute1.png",
    "type": "image",
    "label": "Nya Cute 1"
  },
  {
    "id": "nyacute2",
    "src": "/chat-media/nyacute2.gif",
    "type": "gif",
    "label": "Nya Cute 2"
  },
  {
    "id": "nyacute3",
    "src": "/chat-media/nyacute3.gif",
    "type": "gif",
    "label": "Nya Cute 3"
  },
  {
    "id": "nyacute4",
    "src": "/chat-media/nyacute4.gif",
    "type": "gif",
    "label": "Nya Cute 4"
  },
  {
    "id": "nyacuteaww",
    "src": "/chat-media/nyacuteaww.gif",
    "type": "gif",
    "label": "Nya Cuteaww"
  },
  {
    "id": "nyacutebunny",
    "src": "/chat-media/nyacutebunny.png",
    "type": "image",
    "label": "Nya Cutebunny"
  },
  {
    "id": "nyacutecat",
    "src": "/chat-media/nyacutecat.png",
    "type": "image",
    "label": "Nya Cutecat"
  },
  {
    "id": "nyacutepaws",
    "src": "/chat-media/nyacutepaws.png",
    "type": "image",
    "label": "Nya Cutepaws"
  },
  {
    "id": "nyadance",
    "src": "/chat-media/nyadance.gif",
    "type": "gif",
    "label": "Nya Dance"
  },
  {
    "id": "nyaded",
    "src": "/chat-media/nyaded.gif",
    "type": "gif",
    "label": "Nya Ded"
  },
  {
    "id": "nyadevil",
    "src": "/chat-media/nyadevil.png",
    "type": "image",
    "label": "Nya Devil"
  },
  {
    "id": "nyadonut",
    "src": "/chat-media/nyadonut.png",
    "type": "image",
    "label": "Nya Donut"
  },
  {
    "id": "nyadonut2",
    "src": "/chat-media/nyadonut2.png",
    "type": "image",
    "label": "Nya Donut 2"
  },
  {
    "id": "nyadonut3",
    "src": "/chat-media/nyadonut3.png",
    "type": "image",
    "label": "Nya Donut 3"
  },
  {
    "id": "nyadraw",
    "src": "/chat-media/nyadraw.png",
    "type": "image",
    "label": "Nya Draw"
  },
  {
    "id": "nyadrool",
    "src": "/chat-media/nyadrool.gif",
    "type": "gif",
    "label": "Nya Drool"
  },
  {
    "id": "nyaeat",
    "src": "/chat-media/nyaeat.gif",
    "type": "gif",
    "label": "Nya Eat"
  },
  {
    "id": "nyaeeh",
    "src": "/chat-media/nyaeeh.png",
    "type": "image",
    "label": "Nya Eeh"
  },
  {
    "id": "nyaeggtoast",
    "src": "/chat-media/nyaeggtoast.png",
    "type": "image",
    "label": "Nya Eggtoast"
  },
  {
    "id": "nyaevilqueen",
    "src": "/chat-media/nyaevilqueen.png",
    "type": "image",
    "label": "Nya Evilqueen"
  },
  {
    "id": "nyaexercise",
    "src": "/chat-media/nyaexercise.png",
    "type": "image",
    "label": "Nya Exercise"
  },
  {
    "id": "nyafan",
    "src": "/chat-media/nyafan.png",
    "type": "image",
    "label": "Nya Fan"
  },
  {
    "id": "nyafan2",
    "src": "/chat-media/nyafan2.gif",
    "type": "gif",
    "label": "Nya Fan 2"
  },
  {
    "id": "nyaflick",
    "src": "/chat-media/nyaflick.gif",
    "type": "gif",
    "label": "Nya Flick"
  },
  {
    "id": "nyaflick2",
    "src": "/chat-media/nyaflick2.png",
    "type": "image",
    "label": "Nya Flick 2"
  },
  {
    "id": "nyaflowers",
    "src": "/chat-media/nyaflowers.png",
    "type": "image",
    "label": "Nya Flowers"
  },
  {
    "id": "nyafries",
    "src": "/chat-media/nyafries.png",
    "type": "image",
    "label": "Nya Fries"
  },
  {
    "id": "nyaghost1",
    "src": "/chat-media/nyaghost1.png",
    "type": "image",
    "label": "Nya Ghost 1"
  },
  {
    "id": "nyaghost2",
    "src": "/chat-media/nyaghost2.png",
    "type": "image",
    "label": "Nya Ghost 2"
  },
  {
    "id": "nyagingerbread",
    "src": "/chat-media/nyagingerbread.png",
    "type": "image",
    "label": "Nya Gingerbread"
  },
  {
    "id": "nyaglasses",
    "src": "/chat-media/nyaglasses.gif",
    "type": "gif",
    "label": "Nya Glasses"
  },
  {
    "id": "nyaglasses-1",
    "src": "/chat-media/nyaglasses-1.png",
    "type": "image",
    "label": "Nya Glasses 1"
  },
  {
    "id": "nyagraduation",
    "src": "/chat-media/nyagraduation.png",
    "type": "image",
    "label": "Nya Graduation"
  },
  {
    "id": "nyahappy",
    "src": "/chat-media/nyahappy.gif",
    "type": "gif",
    "label": "Nya Happy"
  },
  {
    "id": "nyaheart",
    "src": "/chat-media/nyaheart.gif",
    "type": "gif",
    "label": "Nya Heart"
  },
  {
    "id": "nyahearts",
    "src": "/chat-media/nyahearts.png",
    "type": "image",
    "label": "Nya Hearts"
  },
  {
    "id": "nyahehe",
    "src": "/chat-media/nyahehe.gif",
    "type": "gif",
    "label": "Nya Hehe"
  },
  {
    "id": "nyahelp",
    "src": "/chat-media/nyahelp.gif",
    "type": "gif",
    "label": "Nya Help"
  },
  {
    "id": "nyahmph1",
    "src": "/chat-media/nyahmph1.gif",
    "type": "gif",
    "label": "Nya Hmph 1"
  },
  {
    "id": "nyahmph2",
    "src": "/chat-media/nyahmph2.png",
    "type": "image",
    "label": "Nya Hmph 2"
  },
  {
    "id": "nyahungry",
    "src": "/chat-media/nyahungry.gif",
    "type": "gif",
    "label": "Nya Hungry"
  },
  {
    "id": "nyahype",
    "src": "/chat-media/nyahype.gif",
    "type": "gif",
    "label": "Nya Hype"
  },
  {
    "id": "nyahype2",
    "src": "/chat-media/nyahype2.gif",
    "type": "gif",
    "label": "Nya Hype 2"
  },
  {
    "id": "nyahyperspin",
    "src": "/chat-media/nyahyperspin.gif",
    "type": "gif",
    "label": "Nya Hyperspin"
  },
  {
    "id": "nyahyperyay",
    "src": "/chat-media/nyahyperyay.gif",
    "type": "gif",
    "label": "Nya Hyperyay"
  },
  {
    "id": "nyaily",
    "src": "/chat-media/nyaily.gif",
    "type": "gif",
    "label": "Nya ILY"
  },
  {
    "id": "nyaicecream",
    "src": "/chat-media/nyaicecream.png",
    "type": "image",
    "label": "Nya Icecream"
  },
  {
    "id": "nyaicecream1",
    "src": "/chat-media/nyaicecream1.png",
    "type": "image",
    "label": "Nya Icecream 1"
  },
  {
    "id": "nyaicecream2",
    "src": "/chat-media/nyaicecream2.png",
    "type": "image",
    "label": "Nya Icecream 2"
  },
  {
    "id": "nyaignorework",
    "src": "/chat-media/nyaignorework.gif",
    "type": "gif",
    "label": "Nya Ignorework"
  },
  {
    "id": "nyajam",
    "src": "/chat-media/nyajam.png",
    "type": "image",
    "label": "Nya Jam"
  },
  {
    "id": "nyakfc",
    "src": "/chat-media/nyakfc.gif",
    "type": "gif",
    "label": "Nya KFC"
  },
  {
    "id": "yay",
    "src": "/chat-media/yay.gif",
    "type": "gif",
    "label": "Yay"
  },
  {
    "id": "nyakiss1",
    "src": "/chat-media/nyakiss1.gif",
    "type": "gif",
    "label": "Nya Kiss 1"
  },
  {
    "id": "nyalaugh1",
    "src": "/chat-media/nyalaugh1.gif",
    "type": "gif",
    "label": "Nya Laugh 1"
  },
  {
    "id": "nyalaugh2",
    "src": "/chat-media/nyalaugh2.gif",
    "type": "gif",
    "label": "Nya Laugh 2"
  },
  {
    "id": "nyalaugh3",
    "src": "/chat-media/nyalaugh3.gif",
    "type": "gif",
    "label": "Nya Laugh 3"
  },
  {
    "id": "nyalazy",
    "src": "/chat-media/nyalazy.gif",
    "type": "gif",
    "label": "Nya Lazy"
  },
  {
    "id": "nyalonely",
    "src": "/chat-media/nyalonely.gif",
    "type": "gif",
    "label": "Nya Lonely"
  },
  {
    "id": "nyalove1",
    "src": "/chat-media/nyalove1.gif",
    "type": "gif",
    "label": "Nya Love 1"
  },
  {
    "id": "nyalove2",
    "src": "/chat-media/nyalove2.gif",
    "type": "gif",
    "label": "Nya Love 2"
  },
  {
    "id": "nyalove3",
    "src": "/chat-media/nyalove3.gif",
    "type": "gif",
    "label": "Nya Love 3"
  },
  {
    "id": "nyalovepls",
    "src": "/chat-media/nyalovepls.gif",
    "type": "gif",
    "label": "Nya Lovepls"
  },
  {
    "id": "nyalurk",
    "src": "/chat-media/nyalurk.gif",
    "type": "gif",
    "label": "Nya Lurk"
  },
  {
    "id": "nyamad",
    "src": "/chat-media/nyamad.gif",
    "type": "gif",
    "label": "Nya Mad"
  },
  {
    "id": "nyamhm",
    "src": "/chat-media/nyamhm.gif",
    "type": "gif",
    "label": "Nya Mhm"
  },
  {
    "id": "nyamooncake",
    "src": "/chat-media/nyamooncake.gif",
    "type": "gif",
    "label": "Nya Mooncake"
  },
  {
    "id": "nyamorning",
    "src": "/chat-media/nyamorning.gif",
    "type": "gif",
    "label": "Nya Morning"
  },
  {
    "id": "nyamwah2",
    "src": "/chat-media/nyamwah2.gif",
    "type": "gif",
    "label": "Nya Mwah 2"
  },
  {
    "id": "nyamwah3",
    "src": "/chat-media/nyamwah3.gif",
    "type": "gif",
    "label": "Nya Mwah 3"
  },
  {
    "id": "nyanana",
    "src": "/chat-media/nyanana.gif",
    "type": "gif",
    "label": "Nya Nana"
  },
  {
    "id": "nyanod1",
    "src": "/chat-media/nyanod1.gif",
    "type": "gif",
    "label": "Nya Nod 1"
  },
  {
    "id": "nyanod2",
    "src": "/chat-media/nyanod2.gif",
    "type": "gif",
    "label": "Nya Nod 2"
  },
  {
    "id": "nyanod3",
    "src": "/chat-media/nyanod3.gif",
    "type": "gif",
    "label": "Nya Nod 3"
  },
  {
    "id": "nyanom2",
    "src": "/chat-media/nyanom2.gif",
    "type": "gif",
    "label": "Nya Nom 2"
  },
  {
    "id": "nyanoodles",
    "src": "/chat-media/nyanoodles.gif",
    "type": "gif",
    "label": "Nya Noodles"
  },
  {
    "id": "nyaparty",
    "src": "/chat-media/nyaparty.gif",
    "type": "gif",
    "label": "Nya Party"
  },
  {
    "id": "nyapat",
    "src": "/chat-media/nyapat.gif",
    "type": "gif",
    "label": "Nya Pat"
  },
  {
    "id": "nyapeace",
    "src": "/chat-media/nyapeace.gif",
    "type": "gif",
    "label": "Nya Peace"
  },
  {
    "id": "nyapeek",
    "src": "/chat-media/nyapeek.gif",
    "type": "gif",
    "label": "Nya Peek"
  },
  {
    "id": "nyapinch",
    "src": "/chat-media/nyapinch.gif",
    "type": "gif",
    "label": "Nya Pinch"
  },
  {
    "id": "nyapinch2",
    "src": "/chat-media/nyapinch2.gif",
    "type": "gif",
    "label": "Nya Pinch 2"
  },
  {
    "id": "nyapizza",
    "src": "/chat-media/nyapizza.gif",
    "type": "gif",
    "label": "Nya Pizza"
  },
  {
    "id": "nyaplease",
    "src": "/chat-media/nyaplease.gif",
    "type": "gif",
    "label": "Nya Please"
  },
  {
    "id": "nyapoint",
    "src": "/chat-media/nyapoint.gif",
    "type": "gif",
    "label": "Nya Point"
  },
  {
    "id": "nyapopcorn",
    "src": "/chat-media/nyapopcorn.gif",
    "type": "gif",
    "label": "Nya Popcorn"
  },
  {
    "id": "nyapout",
    "src": "/chat-media/nyapout.gif",
    "type": "gif",
    "label": "Nya Pout"
  },
  {
    "id": "nyarain",
    "src": "/chat-media/nyarain.gif",
    "type": "gif",
    "label": "Nya Rain"
  },
  {
    "id": "nyarawr",
    "src": "/chat-media/nyarawr.gif",
    "type": "gif",
    "label": "Nya Rawr"
  },
  {
    "id": "nyaregret",
    "src": "/chat-media/nyaregret.gif",
    "type": "gif",
    "label": "Nya Regret"
  },
  {
    "id": "nyarelaxed",
    "src": "/chat-media/nyarelaxed.gif",
    "type": "gif",
    "label": "Nya Relaxed"
  },
  {
    "id": "nyarelaxed2",
    "src": "/chat-media/nyarelaxed2.gif",
    "type": "gif",
    "label": "Nya Relaxed 2"
  },
  {
    "id": "nyasad1",
    "src": "/chat-media/nyasad1.gif",
    "type": "gif",
    "label": "Nya Sad 1"
  },
  {
    "id": "nyashrug",
    "src": "/chat-media/nyashrug.gif",
    "type": "gif",
    "label": "Nya Shrug"
  },
  {
    "id": "nyasit",
    "src": "/chat-media/nyasit.gif",
    "type": "gif",
    "label": "Nya Sit"
  },
  {
    "id": "nyasleep1",
    "src": "/chat-media/nyasleep1.gif",
    "type": "gif",
    "label": "Nya Sleep 1"
  },
  {
    "id": "nyasleep2",
    "src": "/chat-media/nyasleep2.gif",
    "type": "gif",
    "label": "Nya Sleep 2"
  },
  {
    "id": "nyasmile",
    "src": "/chat-media/nyasmile.gif",
    "type": "gif",
    "label": "Nya Smile"
  },
  {
    "id": "nyasmush",
    "src": "/chat-media/nyasmush.gif",
    "type": "gif",
    "label": "Nya Smush"
  },
  {
    "id": "nyasneeze",
    "src": "/chat-media/nyasneeze.gif",
    "type": "gif",
    "label": "Nya Sneeze"
  },
  {
    "id": "nyasob",
    "src": "/chat-media/nyasob.gif",
    "type": "gif",
    "label": "Nya Sob"
  },
  {
    "id": "nyaspin",
    "src": "/chat-media/nyaspin.gif",
    "type": "gif",
    "label": "Nya Spin"
  },
  {
    "id": "nyasuika",
    "src": "/chat-media/nyasuika.gif",
    "type": "gif",
    "label": "Nya Suika"
  },
  {
    "id": "nyatakemymoney",
    "src": "/chat-media/nyatakemymoney.gif",
    "type": "gif",
    "label": "Nya Takemymoney"
  },
  {
    "id": "nyatears",
    "src": "/chat-media/nyatears.gif",
    "type": "gif",
    "label": "Nya Tears"
  },
  {
    "id": "nyatearsbowl",
    "src": "/chat-media/nyatearsbowl.gif",
    "type": "gif",
    "label": "Nya Tearsbowl"
  },
  {
    "id": "nyatease1",
    "src": "/chat-media/nyatease1.gif",
    "type": "gif",
    "label": "Nya Tease 1"
  },
  {
    "id": "nyatease2",
    "src": "/chat-media/nyatease2.gif",
    "type": "gif",
    "label": "Nya Tease 2"
  },
  {
    "id": "nyatext2",
    "src": "/chat-media/nyatext2.gif",
    "type": "gif",
    "label": "Nya Text 2"
  },
  {
    "id": "nyatexts",
    "src": "/chat-media/nyatexts.gif",
    "type": "gif",
    "label": "Nya Texts"
  },
  {
    "id": "nyathink",
    "src": "/chat-media/nyathink.gif",
    "type": "gif",
    "label": "Nya Think"
  },
  {
    "id": "nyathrowconfetti",
    "src": "/chat-media/nyathrowconfetti.gif",
    "type": "gif",
    "label": "Nya Throwconfetti"
  },
  {
    "id": "nyathumbsup",
    "src": "/chat-media/nyathumbsup.gif",
    "type": "gif",
    "label": "Nya Thumbsup"
  },
  {
    "id": "nyatired",
    "src": "/chat-media/nyatired.gif",
    "type": "gif",
    "label": "Nya Tired"
  },
  {
    "id": "nyawalk",
    "src": "/chat-media/nyawalk.gif",
    "type": "gif",
    "label": "Nya Walk"
  },
  {
    "id": "nyawat",
    "src": "/chat-media/nyawat.gif",
    "type": "gif",
    "label": "Nya Wat"
  },
  {
    "id": "nyawave",
    "src": "/chat-media/nyawave.gif",
    "type": "gif",
    "label": "Nya Wave"
  },
  {
    "id": "nyawhat",
    "src": "/chat-media/nyawhat.gif",
    "type": "gif",
    "label": "Nya What"
  },
  {
    "id": "nyawhistle",
    "src": "/chat-media/nyawhistle.gif",
    "type": "gif",
    "label": "Nya Whistle"
  },
  {
    "id": "nyawink",
    "src": "/chat-media/nyawink.gif",
    "type": "gif",
    "label": "Nya Wink"
  },
  {
    "id": "nyayay",
    "src": "/chat-media/nyayay.gif",
    "type": "gif",
    "label": "Nya Yay"
  },
  {
    "id": "nyaabdaycake",
    "src": "/chat-media/nyaabdaycake.gif",
    "type": "gif",
    "label": "Nyaa Bdaycake"
  },
  {
    "id": "nyaaboba2",
    "src": "/chat-media/nyaaboba2.gif",
    "type": "gif",
    "label": "Nyaa Boba 2"
  },
  {
    "id": "nyaabox",
    "src": "/chat-media/nyaabox.gif",
    "type": "gif",
    "label": "Nyaa Box"
  },
  {
    "id": "nyaacall",
    "src": "/chat-media/nyaacall.gif",
    "type": "gif",
    "label": "Nyaa Call"
  },
  {
    "id": "nyaacheer",
    "src": "/chat-media/nyaacheer.gif",
    "type": "gif",
    "label": "Nyaa Cheer"
  },
  {
    "id": "nyaachonk",
    "src": "/chat-media/nyaachonk.gif",
    "type": "gif",
    "label": "Nyaa Chonk"
  },
  {
    "id": "nyaachonk2",
    "src": "/chat-media/nyaachonk2.gif",
    "type": "gif",
    "label": "Nyaa Chonk 2"
  },
  {
    "id": "nyaacomfy",
    "src": "/chat-media/nyaacomfy.gif",
    "type": "gif",
    "label": "Nyaa Comfy"
  },
  {
    "id": "nyaacool",
    "src": "/chat-media/nyaacool.gif",
    "type": "gif",
    "label": "Nyaa Cool"
  },
  {
    "id": "nyaadance",
    "src": "/chat-media/nyaadance.gif",
    "type": "gif",
    "label": "Nyaa Dance"
  },
  {
    "id": "nyaaded",
    "src": "/chat-media/nyaaded.gif",
    "type": "gif",
    "label": "Nyaa Ded"
  },
  {
    "id": "nyaaexercise2",
    "src": "/chat-media/nyaaexercise2.gif",
    "type": "gif",
    "label": "Nyaa Exercise 2"
  },
  {
    "id": "nyaaflower",
    "src": "/chat-media/nyaaflower.gif",
    "type": "gif",
    "label": "Nyaa Flower"
  },
  {
    "id": "nyaaghost",
    "src": "/chat-media/nyaaghost.gif",
    "type": "gif",
    "label": "Nyaa Ghost"
  },
  {
    "id": "nyaagiveup",
    "src": "/chat-media/nyaagiveup.gif",
    "type": "gif",
    "label": "Nyaa Giveup"
  },
  {
    "id": "nyaahearts",
    "src": "/chat-media/nyaahearts.gif",
    "type": "gif",
    "label": "Nyaa Hearts"
  },
  {
    "id": "nyaahype",
    "src": "/chat-media/nyaahype.gif",
    "type": "gif",
    "label": "Nyaa Hype"
  },
  {
    "id": "nyaahype2",
    "src": "/chat-media/nyaahype2.gif",
    "type": "gif",
    "label": "Nyaa Hype 2"
  },
  {
    "id": "nyaaimfine",
    "src": "/chat-media/nyaaimfine.gif",
    "type": "gif",
    "label": "Nyaa Imfine"
  },
  {
    "id": "nyaaking",
    "src": "/chat-media/nyaaking.gif",
    "type": "gif",
    "label": "Nyaa King"
  },
  {
    "id": "nyaakiss1",
    "src": "/chat-media/nyaakiss1.gif",
    "type": "gif",
    "label": "Nyaa Kiss 1"
  },
  {
    "id": "nyaalonelyguitar",
    "src": "/chat-media/nyaalonelyguitar.gif",
    "type": "gif",
    "label": "Nyaa Lonelyguitar"
  },
  {
    "id": "nyaalooking",
    "src": "/chat-media/nyaalooking.gif",
    "type": "gif",
    "label": "Nyaa Looking"
  },
  {
    "id": "nyaalove",
    "src": "/chat-media/nyaalove.gif",
    "type": "gif",
    "label": "Nyaa Love"
  },
  {
    "id": "nyaameow",
    "src": "/chat-media/nyaameow.gif",
    "type": "gif",
    "label": "Nyaa Meow"
  },
  {
    "id": "nyaamooncake",
    "src": "/chat-media/nyaamooncake.gif",
    "type": "gif",
    "label": "Nyaa Mooncake"
  },
  {
    "id": "nyaanod",
    "src": "/chat-media/nyaanod.gif",
    "type": "gif",
    "label": "Nyaa Nod"
  },
  {
    "id": "nyaanoodle",
    "src": "/chat-media/nyaanoodle.gif",
    "type": "gif",
    "label": "Nyaa Noodle"
  },
  {
    "id": "nyaaok",
    "src": "/chat-media/nyaaok.gif",
    "type": "gif",
    "label": "Nyaa Ok"
  },
  {
    "id": "nyaasuika",
    "src": "/chat-media/nyaasuika.gif",
    "type": "gif",
    "label": "Nyaa Suika"
  },
  {
    "id": "nyaatease",
    "src": "/chat-media/nyaatease.gif",
    "type": "gif",
    "label": "Nyaa Tease"
  },
  {
    "id": "nyaathumbsup",
    "src": "/chat-media/nyaathumbsup.gif",
    "type": "gif",
    "label": "Nyaa Thumbsup"
  },
  {
    "id": "nyaavictim",
    "src": "/chat-media/nyaavictim.gif",
    "type": "gif",
    "label": "Nyaa Victim"
  },
  {
    "id": "nyaawave",
    "src": "/chat-media/nyaawave.gif",
    "type": "gif",
    "label": "Nyaa Wave"
  },
  {
    "id": "nyaawave2",
    "src": "/chat-media/nyaawave2.gif",
    "type": "gif",
    "label": "Nyaa Wave 2"
  },
  {
    "id": "nyasbite1-586185650458329119",
    "src": "/chat-media/nyasbite1-586185650458329119.gif",
    "type": "gif",
    "label": "Nyas Bite 1 586185650458329119"
  },
  {
    "id": "nyasbite1",
    "src": "/chat-media/nyasbite1.gif",
    "type": "gif",
    "label": "Nyas Bite 1"
  },
  {
    "id": "nyasbite2",
    "src": "/chat-media/nyasbite2.gif",
    "type": "gif",
    "label": "Nyas Bite 2"
  },
  {
    "id": "nyasbite3",
    "src": "/chat-media/nyasbite3.gif",
    "type": "gif",
    "label": "Nyas Bite 3"
  },
  {
    "id": "nyasbully2",
    "src": "/chat-media/nyasbully2.gif",
    "type": "gif",
    "label": "Nyas Bully 2"
  },
  {
    "id": "nyasbully3",
    "src": "/chat-media/nyasbully3.gif",
    "type": "gif",
    "label": "Nyas Bully 3"
  },
  {
    "id": "nyasbully4",
    "src": "/chat-media/nyasbully4.gif",
    "type": "gif",
    "label": "Nyas Bully 4"
  },
  {
    "id": "nyasbully5",
    "src": "/chat-media/nyasbully5.gif",
    "type": "gif",
    "label": "Nyas Bully 5"
  },
  {
    "id": "nyasbully6",
    "src": "/chat-media/nyasbully6.gif",
    "type": "gif",
    "label": "Nyas Bully 6"
  },
  {
    "id": "nyascarry",
    "src": "/chat-media/nyascarry.gif",
    "type": "gif",
    "label": "Nyas Carry"
  },
  {
    "id": "nyascarry2",
    "src": "/chat-media/nyascarry2.gif",
    "type": "gif",
    "label": "Nyas Carry 2"
  },
  {
    "id": "nyascomfort",
    "src": "/chat-media/nyascomfort.gif",
    "type": "gif",
    "label": "Nyas Comfort"
  },
  {
    "id": "nyascozy1",
    "src": "/chat-media/nyascozy1.gif",
    "type": "gif",
    "label": "Nyas Cozy 1"
  },
  {
    "id": "nyascozy2",
    "src": "/chat-media/nyascozy2.gif",
    "type": "gif",
    "label": "Nyas Cozy 2"
  },
  {
    "id": "nyascry",
    "src": "/chat-media/nyascry.gif",
    "type": "gif",
    "label": "Nyas Cry"
  },
  {
    "id": "nyascuddle",
    "src": "/chat-media/nyascuddle.gif",
    "type": "gif",
    "label": "Nyas Cuddle"
  },
  {
    "id": "nyasdisappointed",
    "src": "/chat-media/nyasdisappointed.gif",
    "type": "gif",
    "label": "Nyas Disappointed"
  },
  {
    "id": "nyasdrag",
    "src": "/chat-media/nyasdrag.gif",
    "type": "gif",
    "label": "Nyas Drag"
  },
  {
    "id": "nyashappy",
    "src": "/chat-media/nyashappy.gif",
    "type": "gif",
    "label": "Nyas Happy"
  },
  {
    "id": "nyashug1",
    "src": "/chat-media/nyashug1.gif",
    "type": "gif",
    "label": "Nyas Hug 1"
  },
  {
    "id": "nyashug2",
    "src": "/chat-media/nyashug2.gif",
    "type": "gif",
    "label": "Nyas Hug 2"
  },
  {
    "id": "nyashug3",
    "src": "/chat-media/nyashug3.gif",
    "type": "gif",
    "label": "Nyas Hug 3"
  },
  {
    "id": "nyashug4",
    "src": "/chat-media/nyashug4.gif",
    "type": "gif",
    "label": "Nyas Hug 4"
  },
  {
    "id": "nyashug6",
    "src": "/chat-media/nyashug6.gif",
    "type": "gif",
    "label": "Nyas Hug 6"
  },
  {
    "id": "nyashug7",
    "src": "/chat-media/nyashug7.gif",
    "type": "gif",
    "label": "Nyas Hug 7"
  },
  {
    "id": "nyaskiss1",
    "src": "/chat-media/nyaskiss1.gif",
    "type": "gif",
    "label": "Nyas Kiss 1"
  },
  {
    "id": "nyaskiss2",
    "src": "/chat-media/nyaskiss2.gif",
    "type": "gif",
    "label": "Nyas Kiss 2"
  },
  {
    "id": "nyaskiss3",
    "src": "/chat-media/nyaskiss3.gif",
    "type": "gif",
    "label": "Nyas Kiss 3"
  },
  {
    "id": "nyaskiss4",
    "src": "/chat-media/nyaskiss4.gif",
    "type": "gif",
    "label": "Nyas Kiss 4"
  },
  {
    "id": "nyaskiss5",
    "src": "/chat-media/nyaskiss5.gif",
    "type": "gif",
    "label": "Nyas Kiss 5"
  },
  {
    "id": "nyaskiss6",
    "src": "/chat-media/nyaskiss6.gif",
    "type": "gif",
    "label": "Nyas Kiss 6"
  },
  {
    "id": "nyaskiss7",
    "src": "/chat-media/nyaskiss7.gif",
    "type": "gif",
    "label": "Nyas Kiss 7"
  },
  {
    "id": "nyaskiss8",
    "src": "/chat-media/nyaskiss8.gif",
    "type": "gif",
    "label": "Nyas Kiss 8"
  },
  {
    "id": "nyaslick",
    "src": "/chat-media/nyaslick.gif",
    "type": "gif",
    "label": "Nyas Lick"
  },
  {
    "id": "nyaslove",
    "src": "/chat-media/nyaslove.gif",
    "type": "gif",
    "label": "Nyas Love"
  },
  {
    "id": "nyasmassage",
    "src": "/chat-media/nyasmassage.gif",
    "type": "gif",
    "label": "Nyas Massage"
  },
  {
    "id": "nyasnoticeme",
    "src": "/chat-media/nyasnoticeme.gif",
    "type": "gif",
    "label": "Nyas Noticeme"
  },
  {
    "id": "nyasnoticeme2",
    "src": "/chat-media/nyasnoticeme2.gif",
    "type": "gif",
    "label": "Nyas Noticeme 2"
  },
  {
    "id": "nyasok",
    "src": "/chat-media/nyasok.gif",
    "type": "gif",
    "label": "Nyas Ok"
  },
  {
    "id": "nyaspat2",
    "src": "/chat-media/nyaspat2.gif",
    "type": "gif",
    "label": "Nyas Pat 2"
  },
  {
    "id": "nyaspat3",
    "src": "/chat-media/nyaspat3.gif",
    "type": "gif",
    "label": "Nyas Pat 3"
  },
  {
    "id": "nyasplayful2",
    "src": "/chat-media/nyasplayful2.gif",
    "type": "gif",
    "label": "Nyas Playful 2"
  },
  {
    "id": "nyasplayful3",
    "src": "/chat-media/nyasplayful3.gif",
    "type": "gif",
    "label": "Nyas Playful 3"
  },
  {
    "id": "nyasplayful4",
    "src": "/chat-media/nyasplayful4.gif",
    "type": "gif",
    "label": "Nyas Playful 4"
  },
  {
    "id": "nyasplayful5",
    "src": "/chat-media/nyasplayful5.gif",
    "type": "gif",
    "label": "Nyas Playful 5"
  },
  {
    "id": "nyasplayful6",
    "src": "/chat-media/nyasplayful6.gif",
    "type": "gif",
    "label": "Nyas Playful 6"
  },
  {
    "id": "nyasslap",
    "src": "/chat-media/nyasslap.gif",
    "type": "gif",
    "label": "Nyas Slap"
  },
  {
    "id": "nyassleep3",
    "src": "/chat-media/nyassleep3.gif",
    "type": "gif",
    "label": "Nyas Sleep 3"
  },
  {
    "id": "nyassmack1",
    "src": "/chat-media/nyassmack1.gif",
    "type": "gif",
    "label": "Nyas Smack 1"
  },
  {
    "id": "nyassmack2",
    "src": "/chat-media/nyassmack2.gif",
    "type": "gif",
    "label": "Nyas Smack 2"
  },
  {
    "id": "nyassnuggle",
    "src": "/chat-media/nyassnuggle.gif",
    "type": "gif",
    "label": "Nyas Snuggle"
  },
  {
    "id": "nyassnuggle2",
    "src": "/chat-media/nyassnuggle2.gif",
    "type": "gif",
    "label": "Nyas Snuggle 2"
  },
  {
    "id": "nyassoothe2",
    "src": "/chat-media/nyassoothe2.gif",
    "type": "gif",
    "label": "Nyas Soothe 2"
  },
  {
    "id": "nyasspank1",
    "src": "/chat-media/nyasspank1.gif",
    "type": "gif",
    "label": "Nyas Spank 1"
  },
  {
    "id": "nyasspank2",
    "src": "/chat-media/nyasspank2.gif",
    "type": "gif",
    "label": "Nyas Spank 2"
  },
  {
    "id": "nyasspin",
    "src": "/chat-media/nyasspin.gif",
    "type": "gif",
    "label": "Nyas Spin"
  },
  {
    "id": "nyasspin2",
    "src": "/chat-media/nyasspin2.gif",
    "type": "gif",
    "label": "Nyas Spin 2"
  }
];

const BY_ID: ReadonlyMap<string, ChatMediaItem> = new Map(CHAT_MEDIA.map((m) => [m.id, m]));

/** The whitelisted media item for an id, or null. Used by the server to validate. */
export function getChatMedia(id: unknown): ChatMediaItem | null {
  return typeof id === 'string' ? (BY_ID.get(id) ?? null) : null;
}
