// ---------------------------------------------------------------------------
// Sound-effect manifest (Stage 15.1). The single source of truth for the MVP
// SFX set under public/sounds/ — used by the guard test now and by the sound
// engine from Stage 15.3 onward.
//
// Assets are PROCEDURAL, royalty-free, DETERMINISTICALLY generated by
// scripts/gen-sound-assets.mjs (dep-free synth → ffmpeg webm/mp3). Each id ships
// as `.webm` (Opus, primary) + `.mp3` (fallback). Ids/character/priority follow
// SOUND_DESIGN.md §3. Pure data — no browser Audio here (playback = Stage 15.3+).
// Fairness: a manifest entry only names a sound; it never carries game state.
// ---------------------------------------------------------------------------

export type SoundCategory = 'ui' | 'card' | 'game' | 'social' | 'finish';
export type SoundPriority = 'P0' | 'P1' | 'P2';

export interface SoundAsset {
  id: string;
  category: SoundCategory;
  priority: SoundPriority;
  /** Primary source: WebM/Opus, served from public/; always starts with '/sounds/'. */
  srcWebm: string;
  /** Fallback source: MP3 (Safari/iOS), served from public/. */
  srcMp3: string;
  /** Guard-test upper bound in bytes, applied to EACH format file. */
  maxBytes: number;
  /** Intended playback duration ceiling (ms) — matches SOUND_DESIGN.md §3. */
  durationMsTarget: number;
  /** Max linear volume the engine should use at the `full` tier (0..1). */
  volumeHint: number;
}

/** Per-file size ceiling (both formats) — SOUND_DESIGN.md §5 "each SFX < 30 KB". */
const PER_FILE_MAX = 30_000;

const A = (
  id: string,
  category: SoundCategory,
  priority: SoundPriority,
  durationMsTarget: number,
  volumeHint: number,
): SoundAsset => ({
  id,
  category,
  priority,
  srcWebm: `/sounds/${id}.webm`,
  srcMp3: `/sounds/${id}.mp3`,
  maxBytes: PER_FILE_MAX,
  durationMsTarget,
  volumeHint,
});

export const SOUND_ASSETS: readonly SoundAsset[] = [
  // UI
  A('ui-click', 'ui', 'P0', 90, 0.5),
  A('ui-open', 'ui', 'P2', 160, 0.4),
  A('ui-error', 'ui', 'P1', 160, 0.5),
  // Cards (shared across games)
  A('card-deal', 'card', 'P1', 80, 0.35),
  A('card-play', 'card', 'P0', 130, 0.5),
  A('trick-collect', 'card', 'P0', 200, 0.5),
  A('trump-reveal', 'card', 'P1', 240, 0.5),
  // Game accents
  A('bid-tick', 'game', 'P1', 90, 0.4),
  // Social
  A('chat-pop', 'social', 'P2', 160, 0.35),
  A('reaction-pop', 'social', 'P2', 140, 0.3),
  // Finish (aligns with WinnerCelebration kinds, Stage 13.7)
  A('finish-win', 'finish', 'P0', 700, 0.6),
  A('finish-neutral', 'finish', 'P1', 500, 0.4),
] as const;

/** Documented ceiling for the TOTAL SFX footprint (all ids × both formats). */
export const SOUND_TOTAL_MAX_BYTES = 500_000;

/** The id union, derived from the manifest for exhaustive typing downstream. */
export type SoundId = (typeof SOUND_ASSETS)[number]['id'];

/** The manifest entry for an id, or null if unknown (never throws). */
export function getSoundAsset(id: string): SoundAsset | null {
  return SOUND_ASSETS.find((a) => a.id === id) ?? null;
}
